-- Project Atlas: The Spark School - Database Schema
-- Run this in the Supabase SQL Editor (https://app.supabase.com/)

-- 1. Create Tables
CREATE TABLE IF NOT EXISTS campuses (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    color_theme TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS faculty (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    role TEXT,
    section TEXT,
    subject TEXT,
    campus_id BIGINT REFERENCES campuses(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS admissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_name TEXT NOT NULL,
    grade_applying TEXT,
    parent_contact TEXT,
    campus_id BIGINT REFERENCES campuses(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS job_positions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT,
    department TEXT,
    campus_id BIGINT REFERENCES campuses(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'Open',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS job_applicants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id BIGINT REFERENCES job_positions(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    resume_url TEXT,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS scoreboard (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campus_id BIGINT REFERENCES campuses(id) ON DELETE CASCADE,
    section TEXT NOT NULL,
    house_name TEXT NOT NULL,
    points BIGINT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(campus_id, section, house_name)
);

-- 2. Disable Row Level Security (RLS) for initial development
-- This allows immediate frontend connectivity without complex policy setup
ALTER TABLE campuses DISABLE ROW LEVEL SECURITY;
ALTER TABLE faculty DISABLE ROW LEVEL SECURITY;
ALTER TABLE admissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_positions DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_applicants DISABLE ROW LEVEL SECURITY;
ALTER TABLE scoreboard DISABLE ROW LEVEL SECURITY;

-- 3. Enable Realtime for scoreboard
-- This allows the frontend to listen for live updates
ALTER PUBLICATION supabase_realtime ADD TABLE scoreboard;
